apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectfour-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: connectfour
  template:
    metadata:
      labels:
        app: connectfour
    spec:
      containers:
      - name: connectfour
        image: yash5090/connectfour:latest
        ports:
        - containerPort: 5000
