apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectfour-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: connectfour
  template:
    metadata:
      labels:
        app: connectfour
    spec:
      containers:
      - name: connectfour
        image: rameshkumarverma/connectfour
        ports:
        - containerPort: 80
