apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-system-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: lms-system
  template:
    metadata:
      labels:
        app: lms-system
    spec:
      containers:
        - name: lms-system
          image: yash5090/lms-system:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
